### ISSUE TITLE
Make the UI more mobile friendly

### ISSUE THREAD

**Issue by dtinth** [dtinth/ThreadGPT#5]
Right now when using ThreadGPT in mobile, each indentation level take up a lot of screen space.

**Comment by fResult** [comment]
Could you brief something for these below?
I already tried to test an App but don't know about it...
- Could the ThreadGPT link to my account on https://openai.chatgpt.com? I can't link them now.
- What is each **thread level** used for?
- What is each **thread** used for? Now, I think it looks like each chat room in https://openai.chatgpt.com
- Now I think I understand for `Generate a Reply` button, but I'm not sure that what `Custom Reply` is used for.
- What is the different of `User`, `Assistant`, and `System` when create a new thread?

![image](https://user-images.githubusercontent.com/19329932/224475551-ca5f3111-6153-4bfd-ae94-3465a3eb360b.png)

**Comment by dtinth** [comment]
@fResult

- You need an OpenAI API key, which you can get from <https://platform.openai.com/> (not ChatGPT[dot]com)
- The thread UI allows your conversation with the AI to **branch into different parallel conversations**.
- **Custom reply** allows you to write your own assistant reply instead of automatically. This can help the assistant to steer in the direction you want.
- For User/Assistant/System please read the documentation here which explains the concepts. https://platform.openai.com/docs/guides/chat

**Comment by dtinth** [comment]
For this particular issue, if the conversation starts to get long, you end up with something like this.

![Screenshot_20230311_165127_Chrome](https://user-images.githubusercontent.com/193136/224477648-ce6962cd-d773-4983-a028-1228ea6a2bf5.jpg)

**Comment by fResult** [comment]
I have fixed. is it okay?

![image](https://user-images.githubusercontent.com/19329932/224483892-e28f77f9-18c7-4d7c-9dae-cbc8bfd9d4df.png)

**Comment by dtinth** [comment]
@fResult Thank you, it looks good, but please check the review comment on the PR krub.

**Comment by dtinth** [comment]
Fixed by

- #13 
- #16
